// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "b65cee12-4e02-4b69-8d98-5f6845ee4e19";

const char SSID[]               = "SECRET_SSID";    // Network SSID (name)
const char PASS[]               = "SECRET_OPTIONAL_PASS";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "KEY" ;    // Secret device password

void onLuz1Change();
void onLuz2Change();

CloudLight luz_1;
CloudLight luz_2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(config.iot_key);
  ArduinoCloud.addProperty(luz_1, READWRITE, ON_CHANGE, onLuz1Change);
  ArduinoCloud.addProperty(luz_2, READWRITE, ON_CHANGE, onLuz2Change);

}


