// Code generated by Arduino IoT Cloud, DO NOT EDIT. ... sure bro hahahaha

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>




void onLuz1Change();
void onLuz2Change();

CloudLight luz_1;
CloudLight luz_2;

void initProperties(){

  ArduinoCloud.setBoardId(config.iot_name);
  ArduinoCloud.setSecretDeviceKey(config.iot_key);
  ArduinoCloud.addProperty(luz_1, READWRITE, ON_CHANGE, onLuz1Change);
  ArduinoCloud.addProperty(luz_2, READWRITE, ON_CHANGE, onLuz2Change);

}



